"""empty message

Revision ID: 05a157edba9c
Revises: 
Create Date: 2020-01-28 13:54:35.350478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05a157edba9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('description', mysql.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
