"""empty message

Revision ID: 217525dd76b5
Revises: 254092debeaf
Create Date: 2020-01-30 13:16:52.978978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217525dd76b5'
down_revision = '254092debeaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('hsn', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'hsn')
    # ### end Alembic commands ###
