"""empty message

Revision ID: b49bc067bc05
Revises: 05a157edba9c
Create Date: 2020-01-28 13:54:46.398030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49bc067bc05'
down_revision = '05a157edba9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('description', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'description')
    # ### end Alembic commands ###
