"""empty message

Revision ID: c016409a7b8b
Revises: b49bc067bc05
Create Date: 2020-01-28 16:59:42.014171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c016409a7b8b'
down_revision = 'b49bc067bc05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('sku', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
